### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by stringparser** [bucaran/gulp-docs-es#3]
Not all weeks I have time to go through the gulp commits and sync the documentation. 

It would be nice to be consistent on a weekly basis.

**Comment by stringparser** [comment]
No update since January... this is not the way to go :). We have to find a solution

**Comment by bucaran** [comment]
How much has the gulp documentation grown in the past few months?

**Comment by stringparser** [comment]
Hahha, is not about growth. Is about stay up to date. The docs will grow when gulp 4.0 takes off but at the moment were all minor changes. Is not fun to do it, and I know it but, one update every two months is not the way to go from my point of view.

**Comment by bucaran** [comment]
> Hahha, is not about growth. 
I thought it was about growth. What is it about?

> Is about stay up to date.
What do you mean? Up to date with what? Is there new material to translate? Can you show me those pages?

**Comment by stringparser** [comment]
Apologies for the delay @bucaran.

No, even after two months the changes to be done (although not really pleasant) weren't that much. So is not about "growth". Up to date meaning: having the docs that are actually in the gulp repo, not something from two-three months ago. 

New? It was updated just now, so there is nothing new now.

**Comment by stringparser** [comment]
@bucaran, I want to apologize. I was an asshole the other day. That wasn't in anyway near to a polite answer. Sorry for that man.

**Comment by bucaran** [comment]
No worries. I plan to do a major revision when gulp 4 is released.
