### ISSUE TITLE
Changelog instead

### ISSUE THREAD

**Issue by stringparser** [bucaran/gulp-docs-es#4]
Use a changelog instead of pointing to the pull requests and/or commit on the commit messages. 

i.e. a commit message would look like this
 - weekly update

instead of
- weekly update gulpjs/gulp#PR1 gulpjs/gulp@commit

Move that useful information to a changelog md file instead

**Comment by stringparser** [comment]
Done, happy new year by the way :+1:

**Comment by bucaran** [comment]
Happy new year for you too! :smile:
